fn main() {
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("macos") {
        cc::Build::new()
            .file("src/native_video.m")
            .file("src/native_font_picker.m")
            .file("src/native_inspector.m")
            .file("src/native_default_app.m")
            .file("src/native_keychain.m")
            .file("src/native_recent_documents.m")
            .file("src/native_updater.m")
            .file("src/native_system_media.m")
            .file("src/native_text_encoding.m")
            .file("src/native_touch_bar.m")
            .file("src/native_localization.m")
            .file("src/native_menu.m")
            .file("src/native_application.m")
            .file("src/native_open_panel.m")
            .file("src/native_prompt.m")
            .file("src/native_file.m")
            .file("src/native_pasteboard.m")
            .file("src/native_window.m")
            .include("../参考/iina/deps/include")
            .define("GL_SILENCE_DEPRECATION", None)
            .flag("-fobjc-arc")
            .flag("-fblocks")
            .compile("iima_native_video");
        println!("cargo:rustc-link-lib=framework=Cocoa");
        println!("cargo:rustc-link-lib=framework=ColorSync");
        println!("cargo:rustc-link-lib=framework=CoreVideo");
        println!("cargo:rustc-link-lib=framework=CoreServices");
        println!("cargo:rustc-link-lib=framework=IOKit");
        println!("cargo:rustc-link-lib=framework=MediaPlayer");
        println!("cargo:rustc-link-lib=framework=OpenGL");
        println!("cargo:rustc-link-lib=framework=QuartzCore");
        println!("cargo:rustc-link-lib=framework=Security");
        println!("cargo:rerun-if-changed=src/native_video.m");
        println!("cargo:rerun-if-changed=src/native_font_picker.m");
        println!("cargo:rerun-if-changed=src/native_inspector.m");
        println!("cargo:rerun-if-changed=src/native_default_app.m");
        println!("cargo:rerun-if-changed=src/native_keychain.m");
        println!("cargo:rerun-if-changed=src/native_recent_documents.m");
        println!("cargo:rerun-if-changed=src/native_updater.m");
        println!("cargo:rerun-if-changed=src/native_system_media.m");
        println!("cargo:rerun-if-changed=src/native_text_encoding.m");
        println!("cargo:rerun-if-changed=src/native_touch_bar.m");
        println!("cargo:rerun-if-changed=src/native_localization.m");
        println!("cargo:rerun-if-changed=src/native-menu-locales.json");
        println!("cargo:rerun-if-changed=src/native_menu.m");
        println!("cargo:rerun-if-changed=src/native_application.m");
        println!("cargo:rerun-if-changed=src/native_open_panel.m");
        println!("cargo:rerun-if-changed=src/native_prompt.m");
        println!("cargo:rerun-if-changed=src/native_file.m");
        println!("cargo:rerun-if-changed=src/native_pasteboard.m");
        println!("cargo:rerun-if-changed=src/native_window.m");
        println!("cargo:rerun-if-changed=../参考/iina/deps/include/mpv/render.h");
        println!("cargo:rerun-if-changed=../参考/iina/deps/include/mpv/render_gl.h");
    }
    tauri_build::build();
}
